### PR TITLE
Fix #11

### LINKED ISSUE #11: Allow infix syntax in `data` declarations
These sorts of things should be valid:

```racket
(data {a :~: b} ...)
(data (List a)
  {a :: (List a)}
  nil)
```

### PR DESCRIPTION
**Pull request by gelisam**

### CODE REVIEW

**Comment by gelisam** [comment]
I noticed that some infix applications use the infix operator more than once, as in `{x <> y <> z}`. I don't think this syntax make sense for either type constructors or data constructors, does it?

**Comment by lexi-lambda** [comment]
Neat! Could you add a small test to `rascal-test/tests/rascal/integration.rkt`? Eventually we’ll have to figure out a better story for a real test suite, but for now just including a simple thing in there is probably helpful. The example you included in your commit message seems like it would be sufficient for a test.

**Comment by gelisam** [comment]
Hmm, why does coveralls still complain? Three times, no less! It looks like the test I added had no effect?

**Comment by lexi-lambda** [comment]
Coveralls is obnoxious and overly loud. I’ve disabled it posting comments on PRs, and I’ve allowed coverage to drop a little bit without being considered a failure. In this case it decreased *0.09%*, which is in the noise. I think this looks fine.

**Comment by lexi-lambda** [comment]
Merged in 7add7bc4a89c73a70ccc277a8f15d3463dbe1da8.

**Pull request closed without merging**
